asdfsafdasf

diff --git a/.github/workflows/action-tests.yml b/.github/workflows/action-tests.yml
--- a/.github/workflows/action-tests.yml
+++ b/.github/workflows/action-tests.yml
@@ -24,6 +24,19 @@ jobs:
         with:
           working-directory: ./test-contracts/hello_foundry
           fail-on: any
+        continue-on-error: true
+
+      - name: Fail the job if the test passed
+        if: success()
+        run: |
+          echo "Test passed, forcing failure"
+          exit 1
+
+      - name: Pass the job if the test failed
+        if: failure()
+        run: |
+          echo "Test failed, forcing pass"
+          exit 0
 
   test-foundry-high-fail:
     name: Actions Test - Foundry-Fail-High
